# docker-compose.yml  (minimal diff)

services:
  api:
    build:
      context: ./api
    container_name: fake-news-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy          # ← this is the only change
      dockerfile: Dockerfile    # (same file, now inside ./proxy)
    container_name: fake-news-proxy
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
