version: '3.8'

services:
  # -----------------------------  API  ----------------------------
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fake-news-api
    ports:
      - "8000:8000"
    depends_on:
      - proxy
    restart: unless-stopped

  # -----------------------------  Nginx proxy  --------------------
  proxy:
    build:
      context: .                    # ✅ FIXED: Now includes web/dist and proxy/
      dockerfile: proxy/Dockerfile
    container_name: fake-news-proxy
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

networks:
  default:
    name: fake-news-net
    driver: bridge
