services:
  - type: web
    name: api
    env: docker
    plan: starter       # $7/mo, free 750h credit on new acct
    dockerfilePath: api/Dockerfile
    autoDeploy: yes
    healthCheckPath: /health
    # optional env for Torch/MPS:
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: proxy
    env: docker
    dockerfilePath: proxy/Dockerfile
    plan: starter
    autoDeploy: yes
    healthCheckPath: /health
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
