# render.yaml  ── Render Blueprint
services:
  # ── FastAPI (API) ───────────────────────────────────────────────
  - type: web
    name: api
    env: docker
    dockerfilePath: api/Dockerfile       # uses your existing Dockerfile
    plan: starter                        # or free if it’s available
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT                        # Render expects $PORT
        value: "8000"

  # ── Nginx + React bundle (Proxy) ────────────────────────────────
  - type: web
    name: proxy
    env: docker
    dockerfilePath: proxy/Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /health            # nginx /health route

